---
title: "Background & Predictions"
---

Insect coloration has evolved in response to multiple pressures, and in dragonflies (Anisoptera) a body of work supports a role of color in a variety of visual signals and potentially in thermoregulation. Wing color has been widely studied for its functions in territorial or sexual signaling, but much less is known about body color - a gap partially due to color fade in museum specimens. Dark body color may assist in the warming of muscles for flight and could also improve immune function in more humid environments, consistent with Gloger's rule. Recent studies have begun to reveal the interplay between not just between climate and color, but also phenology, the seasonal timing of activity. In dragonflies, the timing of adult emergence for the summer mating season strongly determines what climate contexts adults are exposed to during this critical period. The contiguous USA presents a broad gradient well-suited for disentangling phenology-climate-color relationships, as species vary greatly in their climatic niches and the timing of adult emergence and flight. Using a novel semi-automated computer vision pipeline, we quantified the color of in-life dragonfly body segments from iNaturalist images using threshold metrics for dark color. We then tested the hypothesis that dragonfly species in high latitudes that start their summer activity period earlier (when it is the coldest) will exhibit darker bodies.
